# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.graph.clone_graph as module_0


def test_case_0():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = module_0.clone_graph1(undirected_graph_node_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label is None
    assert var_0.neighbors == []


def test_case_1():
    none_type_0 = None
    var_0 = module_0.clone_graph1(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\x1d\xa3Z\xed\xe3V\x05\x0e \x86"
    module_0.clone_graph2(bytes_0)


def test_case_3():
    none_type_0 = None
    var_0 = module_0.clone_graph2(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bool_0 = True
    module_0.clone_graph(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    var_0 = module_0.clone_graph(bool_0)
    none_type_0 = None
    var_0.rpartition(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    none_type_0 = None
    var_0 = module_0.clone_graph(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_1 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label is None
    assert var_1.neighbors == []
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_2 = var_1.shallow_copy()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = module_0.clone_graph(undirected_graph_node_1)
    var_0.count(var_2, end=var_1)


def test_case_7():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = module_0.clone_graph2(none_type_0)
    var_1 = undirected_graph_node_0.add_neighbor(none_type_0)
    var_2 = undirected_graph_node_0.shallow_copy()
    var_3 = module_0.clone_graph1(none_type_0)


def test_case_8():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label is None
    assert var_0.neighbors == []


@pytest.mark.xfail(strict=True)
def test_case_9():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_0.shallow_copy()
    var_1 = module_0.clone_graph2(none_type_0)
    var_2 = undirected_graph_node_0.add_neighbor(none_type_0)
    module_0.clone_graph1(undirected_graph_node_0)


@pytest.mark.xfail(strict=True)
def test_case_10():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = module_0.clone_graph2(undirected_graph_node_1)
    assert (
        f"{type(var_0).__module__}.{type(var_0).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_0.label is None
    assert var_0.neighbors == []
    var_1 = undirected_graph_node_1.add_neighbor(undirected_graph_node_1)
    var_2 = var_0.shallow_copy()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = module_0.clone_graph2(var_2)
    var_4 = var_3.__gt__(none_type_0)
    var_5 = module_0.clone_graph1(undirected_graph_node_1)
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_5.label is None
    assert (
        f"{type(var_5.neighbors).__module__}.{type(var_5.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_5.neighbors) == 1
    module_0.clone_graph(var_4)


@pytest.mark.xfail(strict=True)
def test_case_11():
    none_type_0 = None
    var_0 = module_0.clone_graph(none_type_0)
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_1 = undirected_graph_node_0.add_neighbor(undirected_graph_node_0)
    var_2 = module_0.clone_graph2(undirected_graph_node_0)
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert (
        f"{type(var_2.neighbors).__module__}.{type(var_2.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_2.neighbors) == 1
    var_3 = module_0.clone_graph2(var_0)
    var_4 = var_2.__gt__(var_0)
    var_5 = module_0.clone_graph1(var_0)
    var_6 = module_0.clone_graph(undirected_graph_node_0)
    assert (
        f"{type(var_6).__module__}.{type(var_6).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_6.label is None
    assert (
        f"{type(var_6.neighbors).__module__}.{type(var_6.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_6.neighbors) == 1
    var_0.title()


@pytest.mark.xfail(strict=True)
def test_case_12():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_0.add_neighbor(none_type_0)
    var_1 = module_0.clone_graph2(undirected_graph_node_1)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label is None
    assert var_1.neighbors == []
    var_2 = var_1.shallow_copy()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = var_1.__gt__(undirected_graph_node_0)
    var_4 = module_0.clone_graph1(var_2)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_4.label is None
    assert var_4.neighbors == []
    module_0.clone_graph(undirected_graph_node_0)


@pytest.mark.xfail(strict=True)
def test_case_13():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_0.add_neighbor(none_type_0)
    module_0.clone_graph2(undirected_graph_node_0)


@pytest.mark.xfail(strict=True)
def test_case_14():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_1.add_neighbor(undirected_graph_node_0)
    var_1 = module_0.clone_graph2(undirected_graph_node_1)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label is None
    assert (
        f"{type(var_1.neighbors).__module__}.{type(var_1.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_1.neighbors) == 1
    var_2 = var_1.shallow_copy()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = var_1.__gt__(undirected_graph_node_0)
    var_4 = module_0.clone_graph1(var_2)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_4.label is None
    assert var_4.neighbors == []
    var_5 = module_0.clone_graph(undirected_graph_node_0)
    assert (
        f"{type(var_5).__module__}.{type(var_5).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_5.label is None
    assert var_5.neighbors == []
    var_6 = var_4.__lt__(none_type_0)
    var_7 = module_0.clone_graph(var_1)
    assert (
        f"{type(var_7).__module__}.{type(var_7).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_7.label is None
    assert (
        f"{type(var_7.neighbors).__module__}.{type(var_7.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_7.neighbors) == 1
    var_8 = undirected_graph_node_0.add_neighbor(var_3)
    var_9 = module_0.clone_graph1(none_type_0)
    var_1.clear()


@pytest.mark.xfail(strict=True)
def test_case_15():
    none_type_0 = None
    undirected_graph_node_0 = module_0.UndirectedGraphNode(none_type_0)
    undirected_graph_node_1 = module_0.UndirectedGraphNode(none_type_0)
    var_0 = undirected_graph_node_1.add_neighbor(undirected_graph_node_0)
    var_1 = module_0.clone_graph2(undirected_graph_node_1)
    assert (
        f"{type(var_1).__module__}.{type(var_1).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_1.label is None
    assert (
        f"{type(var_1.neighbors).__module__}.{type(var_1.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_1.neighbors) == 1
    var_2 = var_1.shallow_copy()
    assert (
        f"{type(var_2).__module__}.{type(var_2).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_2.label is None
    assert var_2.neighbors == []
    var_3 = var_2.__gt__(none_type_0)
    var_4 = module_0.clone_graph1(undirected_graph_node_1)
    assert (
        f"{type(var_4).__module__}.{type(var_4).__qualname__}"
        == "algorithms.graph.clone_graph.UndirectedGraphNode"
    )
    assert var_4.label is None
    assert (
        f"{type(var_4.neighbors).__module__}.{type(var_4.neighbors).__qualname__}"
        == "builtins.list"
    )
    assert len(var_4.neighbors) == 1
    var_5 = module_0.clone_graph(var_0)
    var_4.count(undirected_graph_node_0, undirected_graph_node_0)
