# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.dp.longest_increasing as module_0


def test_case_0():
    bytes_0 = b"\xf6\x92\x15\xca@"
    var_0 = module_0.longest_increasing_subsequence(bytes_0)
    assert var_0 == 2


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"#1QY\xa0\x8b%|\xa5\x0e"
    module_0.longest_increasing_subsequence_optimized(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\xf6\x92\x15\xca@"
    module_0.longest_increasing_subsequence_optimized2(bytes_0)


def test_case_3():
    set_0 = set()
    var_0 = module_0.longest_increasing_subsequence_optimized2(set_0)
    assert var_0 == 0


def test_case_4():
    bytes_0 = b"\x8f"
    var_0 = module_0.longest_increasing_subsequence_optimized2(bytes_0)
    assert var_0 == 1


@pytest.mark.xfail(strict=True)
def test_case_5():
    bool_0 = False
    module_0.longest_increasing_subsequence_optimized(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_6():
    bytes_0 = b"#1QY\xa0\x8b\x9a|\xa5\x0e"
    module_0.longest_increasing_subsequence_optimized2(bytes_0)
