# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import algorithms.sort.bubble_sort as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\xd6\xc7\x14\xf0\x1bi%\xdd[\xd7\xdeg\xef_"
    module_0.bubble_sort(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x82\xfd\x89\xa5\xab\xc2\x8f{y*\xbf\xea\xa7\xa2\xee\x1e\x03\xd3"
    module_0.bubble_sort(bytes_0, bytes_0)


def test_case_2():
    set_0 = set()
    var_0 = module_0.bubble_sort(set_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    bytes_0 = b'\xb3\xd1;\xc8\x1bf\x83\xaa"b\xa2\xfc.\xf2\xfd\xd61w'
    module_0.bubble_sort(bytes_0)


def test_case_4():
    int_0 = -521
    tuple_0 = ()
    tuple_1 = (int_0, tuple_0, tuple_0, int_0)
    list_0 = [tuple_1, tuple_0]
    var_0 = module_0.bubble_sort(list_0)


def test_case_5():
    int_0 = -514
    tuple_0 = ()
    tuple_1 = (int_0, tuple_0, tuple_0, int_0)
    list_0 = [tuple_1, tuple_0]
    var_0 = module_0.bubble_sort(list_0, int_0)
    var_1 = module_0.bubble_sort(list_0)
